### ISSUE TITLE
Language file can't contain calculated properties

### ISSUE THREAD

**Issue by mudrd8mz** [GopalSharma/moodle-qformat_csv-master#5]
`$string['pluginname_help']` must be fixed, it can't contain a link based on `$CFG->wwwroot`. See https://docs.moodle.org/dev/String_API#More_help_links on how to use `%%WWWROOT%%.` eventually.

**Comment by GopalSharma** [comment]
I have removed the link, that link was basically to help the user to see the sample file. I have added a page which redirects when clicking on more help to [https://docs.moodle.org/35/en/index.php?title=qformat/csv&redirect=no](https://docs.moodle.org/35/en/index.php?title=qformat/csv&redirect=no)

That page saying pending for review and when clicking it directly from the plugin gives an error like _"This page does not exist_" . Please ask some to review that page which will really help the users.
I'll be providing more details into that document time to time.
